### PR TITLE
Add GH action workflow for IPFS deploys

### PR DESCRIPTION
**Pull request by cap10morgan**
Can someone with permission to do so add the two referenced pinata api secrets to this repo? I have values for them already if you don't, and can send them to you in Keybase.

### CODE REVIEW

**Review by tobowers — APPROVED** [review]
this is pretty cool

**Comment by cap10morgan** [comment]
It works! https://gateway.pinata.cloud/ipfs/QmZSAwF3ABfZrLkPeD9ZtiMdgmgkQC5ngtDdSnyQaAXb4x/

**Comment by cap10morgan** [comment]
@tobowers Cloudflare DNS updates aren't working for some reason, but when I manually update it the new JS HTTPS redirect works. Mind taking another look at the new commits when you have a sec?

**Review by tobowers — APPROVED** [review]
lgtm

**Pull request merged**
